### ISSUE TITLE
OPTMOD for python 3.7 

### ISSUE THREAD

**Issue by TamerSobhy** [ttinoco/OPTMOD#21]
Hey Tomas, 
I am trying to use OPTMOD, When I tried the example I got this error message: 

Traceback (most recent call last):
  File "D:\Code\OPTMOD\tests\test_problems.py", line 21, in test_var_order_consistency
    std_prob = p.__get_std_problem__()
  File "D:\Code\OPTMOD\optmod\problem.py", line 346, in __get_std_problem__
    data[0,i].__fill_evaluator__(e)
  File "D:\Code\OPTMOD\optmod\function.py", line 44, in __fill_evaluator__
    [id(arg) for arg in self.arguments])
  File "optmod\coptmod\evaluator.pyx", line 42, in optmod.coptmod.coptmod.Evaluator.add_node
    x = np.array(arg_ids, dtype=np.int32)
OverflowError: Python int too large to convert to C long

Also when I run nosetests -s -v, I got the same error. 

Best wishes,

**Comment by ttinoco** [comment]
Hi Tamer,
sorry for the late reply. Are you using Windows? I don't think I have tried
building Optmod with windows. It should be possible with the same
procedures as optalg/pfnet, but might need some steps to setup the correct
compiler to use

https://github.com/ttinoco/PFNET.py/blob/master/build_lib.bat#L14
https://github.com/ttinoco/OPTALG/blob/master/build_lib.bat#L20
(this is what optalg/pfnet.py do before building the python extension
module (python setup.py build_ext --inplace), and they rely on mingwpy (see
optalg/pfnet.py pre-requisites in the documentation). I believe Adam has
managed to build pfnet/opalg, possibly also optmod for epri projects for
Python 3 on windows. Maybe you can ask him what he did.

I highly recommend using Linux (especially Ubuntu). I think Windows now
comes with a Ubuntu "subsystem" you may be able to use.
Let me know how it goes.

Tomas

**Comment by TamerSobhy** [comment]
Hey Tomas, 

It works fine in Linux. 
Thank you! 

Tamer
